### ISSUE TITLE
time data - doesn't match format specified

### ISSUE THREAD

**Issue by tamdragle** [hahnicity/ventmode#3]
Hi @hahnicity 
I run project and have an error. I debug and saw in datasets.py file breath[29] doesn't match format. Please help me fix it
```
Run main experiment (Table 3) with Random Forest
Traceback (most recent call last):
  File "main.py", line 944, in <module>
    main()
  File "main.py", line 904, in main
    df = feature_set.create_learning_df()
  File "/Users/tranthanhtam/ventmode/ventmode/datasets.py", line 570, in create_learning_df
    df, all_vwd, all_bm = self.get_features_and_annos()
  File "/Users/tranthanhtam/ventmode/ventmode/datasets.py", line 407, in get_features_and_annos
    x, all_breath_vwd, all_breath_metadata = self.get_features(tor_results=tor_results, random_thresh=random_thresh, dtw_n_lookback=dtw_n_lookback, dtw_thresh=dtw_thresh, dtw_rolling_av_len=dtw_rolling_av_len)
  File "/Users/tranthanhtam/ventmode/ventmode/datasets.py", line 288, in get_features
    abs_bs = pd.to_datetime(breath[29], format='%Y-%m-%d %H:%M:%S.%f')
  File "/Users/tranthanhtam/opt/anaconda3/envs/ventmode/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 611, in to_datetime
    result = convert_listlike(np.array([arg]), box, format)[0]
  File "/Users/tranthanhtam/opt/anaconda3/envs/ventmode/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 302, in _convert_listlike_datetimes
    allow_object=True)
  File "/Users/tranthanhtam/opt/anaconda3/envs/ventmode/lib/python2.7/site-packages/pandas/core/arrays/datetimes.py", line 1866, in objects_to_datetime64ns
    raise e
ValueError: time data - doesn't match format specified
```

**Comment by hahnicity** [comment]
This is a problem with ventmap==1.4. To fix do

```
pip install -U ventmap
```
